apiVersion: v1
kind: Secret
metadata:
  labels: {{ include "sentry-kubernetes.labels" . | indent 4 }}
  name: {{ template "sentry-kubernetes.fullname" . }}
type: Opaque
data:
  {{- range $k, $v := .Values.envsSecret }}
  {{ $k | quote }}: {{ $v | b64enc | quote }}
  {{- end }}
